# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://cciw.github.io'
baseurl: ''
title: 'Workshop on Converged Computing Infrastructure'
description: ''
permalink: pretty
logo: "/images/logo.png"


# Header nav
navigation_header:
  Home: /
  Organization: /about/
  Submission: /submission/

# Footer nav
navigation_footer:
  Back to top: "#top"
