# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://cciw.github.io/2019'
baseurl: ''
title: 'Workshop on Converged Computing Infrastructure'
description: ''
permalink: pretty
logo: "/2019/images/logo.png"


# Header nav
navigation_header:
- title: Home
  url: /2019/
- title: Organization
  url: /2019/about/
- title: Submission
  url: /2019/submission/

# Footer nav
navigation_footer:
  Back to top: "#top"
